export const tarotStyles = {
  drawPage: "tarotDrawPage",
  themeSidebar: "tarotThemeSidebar",
  eyebrow: "tarotEyebrow",
  themeBlock: "tarotThemeBlock",
  sideNote: "tarotSideNote",
  drawStage: "tarotDrawStage",
  spreadSwitch: "tarotSpreadSwitch",
  stageHeader: "tarotStageHeader",
  fanViewport: "tarotFanViewport",
  fanRail: "tarotFanRail",
  fanCard: "tarotFanCard",
  cardArtwork: "tarotCardArtwork",
  slots: "tarotSlots",
  slotColumn: "tarotSlotColumn",
  slotCard: "tarotSlotCard",
  slotMark: "tarotSlotMark",
  revealedArtwork: "tarotRevealedArtwork",
  selectionStatus: "tarotSelectionStatus",
  inlineError: "tarotInlineError",
  redrawLink: "tarotRedrawLink",
  actionFooter: "tarotActionFooter",
  secondaryAction: "tarotSecondaryAction",
  primaryAction: "tarotPrimaryAction",
  loadingPage: "tarotLoadingPage"
} as const;
